font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

  size: 10

key_bindings:
  - { key: P,   mods: Control|Shift,    chars: "\x1bp" }

env:
  TERM: xterm-256color
